development:
  sessions:
    default:
      database: sprechen_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: search_api_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
